[build-system]
build-backend = "mesonpy"
requires = [
    "meson-python >=0.15.0",
    "numpy >= 1.25.0",
]

[project]
name = "fibonacci"
version = "0.1.0"
requires-python = ">= 3.10"
dependencies = [
    "numpy >= 1.25.0",
]


